version: '0'
services: 
  app:
    container_name: api1-Docker
    build: ./api/hello-world-api
    ports:
    - "3000:3000"
    environment:
    - MESSAGE= Daniela Cristina

  app2:
    container_name: api2-Docker
    build: ./api/hello-world-api
    ports:
    - "3001:3000"
    environment:
    - MESSAGE= Aprendiendo Docker Compose

  app3:
    container_name: api3-Docker
    build: ./api/hello-world-api
    ports:
    - "3002:3000"
    environment:
    - MESSAGE= Little Mariposas